---
name: artikulate
version: 17.08.1
summary: Artikulate Pronunciation Trainer
description: Artikulate is a pronunciation trainer that helps improving and perfecting
    a learner's pronunciation skills for a foreign language. It provides courses with
    native speaker recordings for several training languages. The learner downloads
    those courses, selects a category of phrases to train, then starts with recording
    her/his own voice when speaking the phrases and comparing the results to the native
    speaker's recordings by listening to both. By adjusting and repeating the own
    pronunciation, the learner can improve his/her skill.
confinement: strict
grade: stable
apps:
    artikulate:
        command: kf5-launch artikulate
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    artikulate:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libqt5gstreamer-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/artikulate-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
