#!/bin/sh
TMP_HOME=$(mktemp -d)
export HOME="$TMP_HOME"
cleanup () {
    rm -rf "$TMP_HOME"
}
trap cleanup EXIT
xvfb-run -a --server-args="-screen 0 1024x768x24" \
    dbus-run-session -- debian/tests/testsuite.xsession
